---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: post_publish
sections:
- type: heading
  label: Content
- type: jekyll-posts
  label: Posts
  create: documents
  templates:
  - post
- type: jekyll-pages
  label: Pages
  create: documents
  new_doc_ext: ".md"
  templates:
  - information-yml
  - landing-page
  - default
- type: directory
  path: _projects
  label: Projects
  create: all
  match: "*"
  templates:
  - project
- type: document
  path: _data/information.yml
  label: Contact Information
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: jekyll build --drafts --unpublished --future --destination _forestry_site
  publish_command: jekyll build --destination _forestry_site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _forestry
  output_directory: _forestry
